// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ActivityExpedition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from ActivityExpedition.proto</summary>
  public static partial class ActivityExpeditionReflection {

    #region Descriptor
    /// <summary>File descriptor for ActivityExpedition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActivityExpeditionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhBY3Rpdml0eUV4cGVkaXRpb24ucHJvdG8ijAEKEkFjdGl2aXR5RXhwZWRp",
            "dGlvbhITCgtNSU9DS0xGRU9JQRgGIAEoDRITCgtNQkZETUhQT0xHThgFIAEo",
            "AxITCgtMS0RNSlBQT0FIThgNIAEoDRIKCgJpZBgLIAEoDRIWCg5hdmF0YXJf",
            "aWRfbGlzdBgIIAMoDRITCgtGRkxNSEdKQkFQRhgHIAEoDUIeqgIbRWdnTGlu",
            "ay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.ActivityExpedition), global::EggLink.DanhengServer.Proto.ActivityExpedition.Parser, new[]{ "MIOCKLFEOIA", "MBFDMHPOLGN", "LKDMJPPOAHN", "Id", "AvatarIdList", "FFLMHGJBAPF" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActivityExpedition : pb::IMessage<ActivityExpedition>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActivityExpedition> _parser = new pb::MessageParser<ActivityExpedition>(() => new ActivityExpedition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActivityExpedition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.ActivityExpeditionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityExpedition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityExpedition(ActivityExpedition other) : this() {
      mIOCKLFEOIA_ = other.mIOCKLFEOIA_;
      mBFDMHPOLGN_ = other.mBFDMHPOLGN_;
      lKDMJPPOAHN_ = other.lKDMJPPOAHN_;
      id_ = other.id_;
      avatarIdList_ = other.avatarIdList_.Clone();
      fFLMHGJBAPF_ = other.fFLMHGJBAPF_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityExpedition Clone() {
      return new ActivityExpedition(this);
    }

    /// <summary>Field number for the "MIOCKLFEOIA" field.</summary>
    public const int MIOCKLFEOIAFieldNumber = 6;
    private uint mIOCKLFEOIA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MIOCKLFEOIA {
      get { return mIOCKLFEOIA_; }
      set {
        mIOCKLFEOIA_ = value;
      }
    }

    /// <summary>Field number for the "MBFDMHPOLGN" field.</summary>
    public const int MBFDMHPOLGNFieldNumber = 5;
    private long mBFDMHPOLGN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MBFDMHPOLGN {
      get { return mBFDMHPOLGN_; }
      set {
        mBFDMHPOLGN_ = value;
      }
    }

    /// <summary>Field number for the "LKDMJPPOAHN" field.</summary>
    public const int LKDMJPPOAHNFieldNumber = 13;
    private uint lKDMJPPOAHN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LKDMJPPOAHN {
      get { return lKDMJPPOAHN_; }
      set {
        lKDMJPPOAHN_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 11;
    private uint id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "avatar_id_list" field.</summary>
    public const int AvatarIdListFieldNumber = 8;
    private static readonly pb::FieldCodec<uint> _repeated_avatarIdList_codec
        = pb::FieldCodec.ForUInt32(66);
    private readonly pbc::RepeatedField<uint> avatarIdList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> AvatarIdList {
      get { return avatarIdList_; }
    }

    /// <summary>Field number for the "FFLMHGJBAPF" field.</summary>
    public const int FFLMHGJBAPFFieldNumber = 7;
    private uint fFLMHGJBAPF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FFLMHGJBAPF {
      get { return fFLMHGJBAPF_; }
      set {
        fFLMHGJBAPF_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActivityExpedition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActivityExpedition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MIOCKLFEOIA != other.MIOCKLFEOIA) return false;
      if (MBFDMHPOLGN != other.MBFDMHPOLGN) return false;
      if (LKDMJPPOAHN != other.LKDMJPPOAHN) return false;
      if (Id != other.Id) return false;
      if(!avatarIdList_.Equals(other.avatarIdList_)) return false;
      if (FFLMHGJBAPF != other.FFLMHGJBAPF) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MIOCKLFEOIA != 0) hash ^= MIOCKLFEOIA.GetHashCode();
      if (MBFDMHPOLGN != 0L) hash ^= MBFDMHPOLGN.GetHashCode();
      if (LKDMJPPOAHN != 0) hash ^= LKDMJPPOAHN.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      hash ^= avatarIdList_.GetHashCode();
      if (FFLMHGJBAPF != 0) hash ^= FFLMHGJBAPF.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MBFDMHPOLGN != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(MBFDMHPOLGN);
      }
      if (MIOCKLFEOIA != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(MIOCKLFEOIA);
      }
      if (FFLMHGJBAPF != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(FFLMHGJBAPF);
      }
      avatarIdList_.WriteTo(output, _repeated_avatarIdList_codec);
      if (Id != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Id);
      }
      if (LKDMJPPOAHN != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(LKDMJPPOAHN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MBFDMHPOLGN != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(MBFDMHPOLGN);
      }
      if (MIOCKLFEOIA != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(MIOCKLFEOIA);
      }
      if (FFLMHGJBAPF != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(FFLMHGJBAPF);
      }
      avatarIdList_.WriteTo(ref output, _repeated_avatarIdList_codec);
      if (Id != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Id);
      }
      if (LKDMJPPOAHN != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(LKDMJPPOAHN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MIOCKLFEOIA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MIOCKLFEOIA);
      }
      if (MBFDMHPOLGN != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MBFDMHPOLGN);
      }
      if (LKDMJPPOAHN != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LKDMJPPOAHN);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      size += avatarIdList_.CalculateSize(_repeated_avatarIdList_codec);
      if (FFLMHGJBAPF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FFLMHGJBAPF);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActivityExpedition other) {
      if (other == null) {
        return;
      }
      if (other.MIOCKLFEOIA != 0) {
        MIOCKLFEOIA = other.MIOCKLFEOIA;
      }
      if (other.MBFDMHPOLGN != 0L) {
        MBFDMHPOLGN = other.MBFDMHPOLGN;
      }
      if (other.LKDMJPPOAHN != 0) {
        LKDMJPPOAHN = other.LKDMJPPOAHN;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      avatarIdList_.Add(other.avatarIdList_);
      if (other.FFLMHGJBAPF != 0) {
        FFLMHGJBAPF = other.FFLMHGJBAPF;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 40: {
            MBFDMHPOLGN = input.ReadInt64();
            break;
          }
          case 48: {
            MIOCKLFEOIA = input.ReadUInt32();
            break;
          }
          case 56: {
            FFLMHGJBAPF = input.ReadUInt32();
            break;
          }
          case 66:
          case 64: {
            avatarIdList_.AddEntriesFrom(input, _repeated_avatarIdList_codec);
            break;
          }
          case 88: {
            Id = input.ReadUInt32();
            break;
          }
          case 104: {
            LKDMJPPOAHN = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 40: {
            MBFDMHPOLGN = input.ReadInt64();
            break;
          }
          case 48: {
            MIOCKLFEOIA = input.ReadUInt32();
            break;
          }
          case 56: {
            FFLMHGJBAPF = input.ReadUInt32();
            break;
          }
          case 66:
          case 64: {
            avatarIdList_.AddEntriesFrom(ref input, _repeated_avatarIdList_codec);
            break;
          }
          case 88: {
            Id = input.ReadUInt32();
            break;
          }
          case 104: {
            LKDMJPPOAHN = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
