// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChessRogueCellSpecialType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from ChessRogueCellSpecialType.proto</summary>
  public static partial class ChessRogueCellSpecialTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for ChessRogueCellSpecialType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChessRogueCellSpecialTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9DaGVzc1JvZ3VlQ2VsbFNwZWNpYWxUeXBlLnByb3RvKpgCChlDaGVzc1Jv",
            "Z3VlQ2VsbFNwZWNpYWxUeXBlEiYKIkNIRVNTX1JPR1VFX0NFTExfU1BFQ0lB",
            "TF9UWVBFX05PTkUQABIoCiRDSEVTU19ST0dVRV9DRUxMX1NQRUNJQUxfVFlQ",
            "RV9MT0NLRUQQARIrCidDSEVTU19ST0dVRV9DRUxMX1NQRUNJQUxfVFlQRV9S",
            "RVBMSUNBVEUQAhIrCidDSEVTU19ST0dVRV9DRUxMX1NQRUNJQUxfVFlQRV9Q",
            "Uk9URUNURUQQAxImCiJDSEVTU19ST0dVRV9DRUxMX1NQRUNJQUxfVFlQRV9T",
            "RUVEEAQSJwojQ0hFU1NfUk9HVUVfQ0VMTF9TUEVDSUFMX1RZUEVfU1RBTVAQ",
            "BUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EggLink.DanhengServer.Proto.ChessRogueCellSpecialType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ChessRogueCellSpecialType {
    [pbr::OriginalName("CHESS_ROGUE_CELL_SPECIAL_TYPE_NONE")] None = 0,
    [pbr::OriginalName("CHESS_ROGUE_CELL_SPECIAL_TYPE_LOCKED")] Locked = 1,
    [pbr::OriginalName("CHESS_ROGUE_CELL_SPECIAL_TYPE_REPLICATE")] Replicate = 2,
    [pbr::OriginalName("CHESS_ROGUE_CELL_SPECIAL_TYPE_PROTECTED")] Protected = 3,
    [pbr::OriginalName("CHESS_ROGUE_CELL_SPECIAL_TYPE_SEED")] Seed = 4,
    [pbr::OriginalName("CHESS_ROGUE_CELL_SPECIAL_TYPE_STAMP")] Stamp = 5,
  }

  #endregion

}

#endregion Designer generated code
