// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EHOELLPNCFK.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from EHOELLPNCFK.proto</summary>
  public static partial class EHOELLPNCFKReflection {

    #region Descriptor
    /// <summary>File descriptor for EHOELLPNCFK.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EHOELLPNCFKReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFFSE9FTExQTkNGSy5wcm90byKLAQoLRUhPRUxMUE5DRksSEwoLQUpCTkdE",
            "Rk5IRVAYCiABKA0SEwoLTUFFTU9OTERDREwYCSABKAgSEwoLTkxHSktBRERG",
            "RFAYDiADKA0SEwoLRUZGR0ZQRE1IS04YDyABKA0SEwoLTEFKSUVPRENPS0cY",
            "BSADKA0SEwoLTklHTkJMUFBDT0oYDSABKA1CHqoCG0VnZ0xpbmsuRGFuaGVu",
            "Z1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.EHOELLPNCFK), global::EggLink.DanhengServer.Proto.EHOELLPNCFK.Parser, new[]{ "AJBNGDFNHEP", "MAEMONLDCDL", "NLGJKADDFDP", "EFFGFPDMHKN", "LAJIEODCOKG", "NIGNBLPPCOJ" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EHOELLPNCFK : pb::IMessage<EHOELLPNCFK>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EHOELLPNCFK> _parser = new pb::MessageParser<EHOELLPNCFK>(() => new EHOELLPNCFK());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EHOELLPNCFK> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.EHOELLPNCFKReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EHOELLPNCFK() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EHOELLPNCFK(EHOELLPNCFK other) : this() {
      aJBNGDFNHEP_ = other.aJBNGDFNHEP_;
      mAEMONLDCDL_ = other.mAEMONLDCDL_;
      nLGJKADDFDP_ = other.nLGJKADDFDP_.Clone();
      eFFGFPDMHKN_ = other.eFFGFPDMHKN_;
      lAJIEODCOKG_ = other.lAJIEODCOKG_.Clone();
      nIGNBLPPCOJ_ = other.nIGNBLPPCOJ_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EHOELLPNCFK Clone() {
      return new EHOELLPNCFK(this);
    }

    /// <summary>Field number for the "AJBNGDFNHEP" field.</summary>
    public const int AJBNGDFNHEPFieldNumber = 10;
    private uint aJBNGDFNHEP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AJBNGDFNHEP {
      get { return aJBNGDFNHEP_; }
      set {
        aJBNGDFNHEP_ = value;
      }
    }

    /// <summary>Field number for the "MAEMONLDCDL" field.</summary>
    public const int MAEMONLDCDLFieldNumber = 9;
    private bool mAEMONLDCDL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MAEMONLDCDL {
      get { return mAEMONLDCDL_; }
      set {
        mAEMONLDCDL_ = value;
      }
    }

    /// <summary>Field number for the "NLGJKADDFDP" field.</summary>
    public const int NLGJKADDFDPFieldNumber = 14;
    private static readonly pb::FieldCodec<uint> _repeated_nLGJKADDFDP_codec
        = pb::FieldCodec.ForUInt32(114);
    private readonly pbc::RepeatedField<uint> nLGJKADDFDP_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> NLGJKADDFDP {
      get { return nLGJKADDFDP_; }
    }

    /// <summary>Field number for the "EFFGFPDMHKN" field.</summary>
    public const int EFFGFPDMHKNFieldNumber = 15;
    private uint eFFGFPDMHKN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EFFGFPDMHKN {
      get { return eFFGFPDMHKN_; }
      set {
        eFFGFPDMHKN_ = value;
      }
    }

    /// <summary>Field number for the "LAJIEODCOKG" field.</summary>
    public const int LAJIEODCOKGFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_lAJIEODCOKG_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> lAJIEODCOKG_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> LAJIEODCOKG {
      get { return lAJIEODCOKG_; }
    }

    /// <summary>Field number for the "NIGNBLPPCOJ" field.</summary>
    public const int NIGNBLPPCOJFieldNumber = 13;
    private uint nIGNBLPPCOJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NIGNBLPPCOJ {
      get { return nIGNBLPPCOJ_; }
      set {
        nIGNBLPPCOJ_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EHOELLPNCFK);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EHOELLPNCFK other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AJBNGDFNHEP != other.AJBNGDFNHEP) return false;
      if (MAEMONLDCDL != other.MAEMONLDCDL) return false;
      if(!nLGJKADDFDP_.Equals(other.nLGJKADDFDP_)) return false;
      if (EFFGFPDMHKN != other.EFFGFPDMHKN) return false;
      if(!lAJIEODCOKG_.Equals(other.lAJIEODCOKG_)) return false;
      if (NIGNBLPPCOJ != other.NIGNBLPPCOJ) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AJBNGDFNHEP != 0) hash ^= AJBNGDFNHEP.GetHashCode();
      if (MAEMONLDCDL != false) hash ^= MAEMONLDCDL.GetHashCode();
      hash ^= nLGJKADDFDP_.GetHashCode();
      if (EFFGFPDMHKN != 0) hash ^= EFFGFPDMHKN.GetHashCode();
      hash ^= lAJIEODCOKG_.GetHashCode();
      if (NIGNBLPPCOJ != 0) hash ^= NIGNBLPPCOJ.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      lAJIEODCOKG_.WriteTo(output, _repeated_lAJIEODCOKG_codec);
      if (MAEMONLDCDL != false) {
        output.WriteRawTag(72);
        output.WriteBool(MAEMONLDCDL);
      }
      if (AJBNGDFNHEP != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(AJBNGDFNHEP);
      }
      if (NIGNBLPPCOJ != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(NIGNBLPPCOJ);
      }
      nLGJKADDFDP_.WriteTo(output, _repeated_nLGJKADDFDP_codec);
      if (EFFGFPDMHKN != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(EFFGFPDMHKN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      lAJIEODCOKG_.WriteTo(ref output, _repeated_lAJIEODCOKG_codec);
      if (MAEMONLDCDL != false) {
        output.WriteRawTag(72);
        output.WriteBool(MAEMONLDCDL);
      }
      if (AJBNGDFNHEP != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(AJBNGDFNHEP);
      }
      if (NIGNBLPPCOJ != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(NIGNBLPPCOJ);
      }
      nLGJKADDFDP_.WriteTo(ref output, _repeated_nLGJKADDFDP_codec);
      if (EFFGFPDMHKN != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(EFFGFPDMHKN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AJBNGDFNHEP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AJBNGDFNHEP);
      }
      if (MAEMONLDCDL != false) {
        size += 1 + 1;
      }
      size += nLGJKADDFDP_.CalculateSize(_repeated_nLGJKADDFDP_codec);
      if (EFFGFPDMHKN != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EFFGFPDMHKN);
      }
      size += lAJIEODCOKG_.CalculateSize(_repeated_lAJIEODCOKG_codec);
      if (NIGNBLPPCOJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NIGNBLPPCOJ);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EHOELLPNCFK other) {
      if (other == null) {
        return;
      }
      if (other.AJBNGDFNHEP != 0) {
        AJBNGDFNHEP = other.AJBNGDFNHEP;
      }
      if (other.MAEMONLDCDL != false) {
        MAEMONLDCDL = other.MAEMONLDCDL;
      }
      nLGJKADDFDP_.Add(other.nLGJKADDFDP_);
      if (other.EFFGFPDMHKN != 0) {
        EFFGFPDMHKN = other.EFFGFPDMHKN;
      }
      lAJIEODCOKG_.Add(other.lAJIEODCOKG_);
      if (other.NIGNBLPPCOJ != 0) {
        NIGNBLPPCOJ = other.NIGNBLPPCOJ;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 42:
          case 40: {
            lAJIEODCOKG_.AddEntriesFrom(input, _repeated_lAJIEODCOKG_codec);
            break;
          }
          case 72: {
            MAEMONLDCDL = input.ReadBool();
            break;
          }
          case 80: {
            AJBNGDFNHEP = input.ReadUInt32();
            break;
          }
          case 104: {
            NIGNBLPPCOJ = input.ReadUInt32();
            break;
          }
          case 114:
          case 112: {
            nLGJKADDFDP_.AddEntriesFrom(input, _repeated_nLGJKADDFDP_codec);
            break;
          }
          case 120: {
            EFFGFPDMHKN = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 42:
          case 40: {
            lAJIEODCOKG_.AddEntriesFrom(ref input, _repeated_lAJIEODCOKG_codec);
            break;
          }
          case 72: {
            MAEMONLDCDL = input.ReadBool();
            break;
          }
          case 80: {
            AJBNGDFNHEP = input.ReadUInt32();
            break;
          }
          case 104: {
            NIGNBLPPCOJ = input.ReadUInt32();
            break;
          }
          case 114:
          case 112: {
            nLGJKADDFDP_.AddEntriesFrom(ref input, _repeated_nLGJKADDFDP_codec);
            break;
          }
          case 120: {
            EFFGFPDMHKN = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
