// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EnterSceneScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from EnterSceneScRsp.proto</summary>
  public static partial class EnterSceneScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for EnterSceneScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnterSceneScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVFbnRlclNjZW5lU2NSc3AucHJvdG8idwoPRW50ZXJTY2VuZVNjUnNwEhoK",
            "EmdhbWVfc3RvcnlfbGluZV9pZBgGIAEoDRITCgtKREFMREpQRk5NThgEIAEo",
            "CBIPCgdyZXRjb2RlGAkgASgNEg4KBm1hcF90cBgIIAEoCBISCgpjb250ZW50",
            "X2lkGAUgASgNQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.EnterSceneScRsp), global::EggLink.DanhengServer.Proto.EnterSceneScRsp.Parser, new[]{ "GameStoryLineId", "JDALDJPFNMN", "Retcode", "MapTp", "ContentId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EnterSceneScRsp : pb::IMessage<EnterSceneScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EnterSceneScRsp> _parser = new pb::MessageParser<EnterSceneScRsp>(() => new EnterSceneScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EnterSceneScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.EnterSceneScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnterSceneScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnterSceneScRsp(EnterSceneScRsp other) : this() {
      gameStoryLineId_ = other.gameStoryLineId_;
      jDALDJPFNMN_ = other.jDALDJPFNMN_;
      retcode_ = other.retcode_;
      mapTp_ = other.mapTp_;
      contentId_ = other.contentId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnterSceneScRsp Clone() {
      return new EnterSceneScRsp(this);
    }

    /// <summary>Field number for the "game_story_line_id" field.</summary>
    public const int GameStoryLineIdFieldNumber = 6;
    private uint gameStoryLineId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GameStoryLineId {
      get { return gameStoryLineId_; }
      set {
        gameStoryLineId_ = value;
      }
    }

    /// <summary>Field number for the "JDALDJPFNMN" field.</summary>
    public const int JDALDJPFNMNFieldNumber = 4;
    private bool jDALDJPFNMN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool JDALDJPFNMN {
      get { return jDALDJPFNMN_; }
      set {
        jDALDJPFNMN_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 9;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "map_tp" field.</summary>
    public const int MapTpFieldNumber = 8;
    private bool mapTp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MapTp {
      get { return mapTp_; }
      set {
        mapTp_ = value;
      }
    }

    /// <summary>Field number for the "content_id" field.</summary>
    public const int ContentIdFieldNumber = 5;
    private uint contentId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ContentId {
      get { return contentId_; }
      set {
        contentId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EnterSceneScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EnterSceneScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameStoryLineId != other.GameStoryLineId) return false;
      if (JDALDJPFNMN != other.JDALDJPFNMN) return false;
      if (Retcode != other.Retcode) return false;
      if (MapTp != other.MapTp) return false;
      if (ContentId != other.ContentId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameStoryLineId != 0) hash ^= GameStoryLineId.GetHashCode();
      if (JDALDJPFNMN != false) hash ^= JDALDJPFNMN.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (MapTp != false) hash ^= MapTp.GetHashCode();
      if (ContentId != 0) hash ^= ContentId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (JDALDJPFNMN != false) {
        output.WriteRawTag(32);
        output.WriteBool(JDALDJPFNMN);
      }
      if (ContentId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(ContentId);
      }
      if (GameStoryLineId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(GameStoryLineId);
      }
      if (MapTp != false) {
        output.WriteRawTag(64);
        output.WriteBool(MapTp);
      }
      if (Retcode != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (JDALDJPFNMN != false) {
        output.WriteRawTag(32);
        output.WriteBool(JDALDJPFNMN);
      }
      if (ContentId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(ContentId);
      }
      if (GameStoryLineId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(GameStoryLineId);
      }
      if (MapTp != false) {
        output.WriteRawTag(64);
        output.WriteBool(MapTp);
      }
      if (Retcode != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameStoryLineId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GameStoryLineId);
      }
      if (JDALDJPFNMN != false) {
        size += 1 + 1;
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (MapTp != false) {
        size += 1 + 1;
      }
      if (ContentId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ContentId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EnterSceneScRsp other) {
      if (other == null) {
        return;
      }
      if (other.GameStoryLineId != 0) {
        GameStoryLineId = other.GameStoryLineId;
      }
      if (other.JDALDJPFNMN != false) {
        JDALDJPFNMN = other.JDALDJPFNMN;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.MapTp != false) {
        MapTp = other.MapTp;
      }
      if (other.ContentId != 0) {
        ContentId = other.ContentId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 32: {
            JDALDJPFNMN = input.ReadBool();
            break;
          }
          case 40: {
            ContentId = input.ReadUInt32();
            break;
          }
          case 48: {
            GameStoryLineId = input.ReadUInt32();
            break;
          }
          case 64: {
            MapTp = input.ReadBool();
            break;
          }
          case 72: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 32: {
            JDALDJPFNMN = input.ReadBool();
            break;
          }
          case 40: {
            ContentId = input.ReadUInt32();
            break;
          }
          case 48: {
            GameStoryLineId = input.ReadUInt32();
            break;
          }
          case 64: {
            MapTp = input.ReadBool();
            break;
          }
          case 72: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
