// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FODJFBNFPJC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from FODJFBNFPJC.proto</summary>
  public static partial class FODJFBNFPJCReflection {

    #region Descriptor
    /// <summary>File descriptor for FODJFBNFPJC.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FODJFBNFPJCReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFGT0RKRkJORlBKQy5wcm90bxoRSEtNQ01GQ09OTk4ucHJvdG8iwgEKC0ZP",
            "REpGQk5GUEpDEhMKC0lNR0lMTk5LR0VLGAkgASgIEhMKC0dHUExLQkZCUE5Q",
            "GAggASgNEiAKCWJ1ZmZfbGlzdBjoBSADKAsyDC5IS01DTUZDT05OThITCgtN",
            "S0tJQkROQk5GRRgOIAEoCBITCgtFRktORUFJUEdMRhgFIAEoCBITCgtMTUNC",
            "RkRBRk1QUBgPIAEoCBITCgtMR09PT01HSktISBgKIAEoDRITCgtIS09HQ1BO",
            "SE5DQRgLIAEoDUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.HKMCMFCONNNReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.FODJFBNFPJC), global::EggLink.DanhengServer.Proto.FODJFBNFPJC.Parser, new[]{ "IMGILNNKGEK", "GGPLKBFBPNP", "BuffList", "MKKIBDNBNFE", "EFKNEAIPGLF", "LMCBFDAFMPP", "LGOOOMGJKHH", "HKOGCPNHNCA" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FODJFBNFPJC : pb::IMessage<FODJFBNFPJC>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FODJFBNFPJC> _parser = new pb::MessageParser<FODJFBNFPJC>(() => new FODJFBNFPJC());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FODJFBNFPJC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.FODJFBNFPJCReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FODJFBNFPJC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FODJFBNFPJC(FODJFBNFPJC other) : this() {
      iMGILNNKGEK_ = other.iMGILNNKGEK_;
      gGPLKBFBPNP_ = other.gGPLKBFBPNP_;
      buffList_ = other.buffList_.Clone();
      mKKIBDNBNFE_ = other.mKKIBDNBNFE_;
      eFKNEAIPGLF_ = other.eFKNEAIPGLF_;
      lMCBFDAFMPP_ = other.lMCBFDAFMPP_;
      lGOOOMGJKHH_ = other.lGOOOMGJKHH_;
      hKOGCPNHNCA_ = other.hKOGCPNHNCA_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FODJFBNFPJC Clone() {
      return new FODJFBNFPJC(this);
    }

    /// <summary>Field number for the "IMGILNNKGEK" field.</summary>
    public const int IMGILNNKGEKFieldNumber = 9;
    private bool iMGILNNKGEK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IMGILNNKGEK {
      get { return iMGILNNKGEK_; }
      set {
        iMGILNNKGEK_ = value;
      }
    }

    /// <summary>Field number for the "GGPLKBFBPNP" field.</summary>
    public const int GGPLKBFBPNPFieldNumber = 8;
    private uint gGPLKBFBPNP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GGPLKBFBPNP {
      get { return gGPLKBFBPNP_; }
      set {
        gGPLKBFBPNP_ = value;
      }
    }

    /// <summary>Field number for the "buff_list" field.</summary>
    public const int BuffListFieldNumber = 744;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.HKMCMFCONNN> _repeated_buffList_codec
        = pb::FieldCodec.ForMessage(5954, global::EggLink.DanhengServer.Proto.HKMCMFCONNN.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HKMCMFCONNN> buffList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HKMCMFCONNN>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HKMCMFCONNN> BuffList {
      get { return buffList_; }
    }

    /// <summary>Field number for the "MKKIBDNBNFE" field.</summary>
    public const int MKKIBDNBNFEFieldNumber = 14;
    private bool mKKIBDNBNFE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MKKIBDNBNFE {
      get { return mKKIBDNBNFE_; }
      set {
        mKKIBDNBNFE_ = value;
      }
    }

    /// <summary>Field number for the "EFKNEAIPGLF" field.</summary>
    public const int EFKNEAIPGLFFieldNumber = 5;
    private bool eFKNEAIPGLF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EFKNEAIPGLF {
      get { return eFKNEAIPGLF_; }
      set {
        eFKNEAIPGLF_ = value;
      }
    }

    /// <summary>Field number for the "LMCBFDAFMPP" field.</summary>
    public const int LMCBFDAFMPPFieldNumber = 15;
    private bool lMCBFDAFMPP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LMCBFDAFMPP {
      get { return lMCBFDAFMPP_; }
      set {
        lMCBFDAFMPP_ = value;
      }
    }

    /// <summary>Field number for the "LGOOOMGJKHH" field.</summary>
    public const int LGOOOMGJKHHFieldNumber = 10;
    private uint lGOOOMGJKHH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LGOOOMGJKHH {
      get { return lGOOOMGJKHH_; }
      set {
        lGOOOMGJKHH_ = value;
      }
    }

    /// <summary>Field number for the "HKOGCPNHNCA" field.</summary>
    public const int HKOGCPNHNCAFieldNumber = 11;
    private uint hKOGCPNHNCA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HKOGCPNHNCA {
      get { return hKOGCPNHNCA_; }
      set {
        hKOGCPNHNCA_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FODJFBNFPJC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FODJFBNFPJC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IMGILNNKGEK != other.IMGILNNKGEK) return false;
      if (GGPLKBFBPNP != other.GGPLKBFBPNP) return false;
      if(!buffList_.Equals(other.buffList_)) return false;
      if (MKKIBDNBNFE != other.MKKIBDNBNFE) return false;
      if (EFKNEAIPGLF != other.EFKNEAIPGLF) return false;
      if (LMCBFDAFMPP != other.LMCBFDAFMPP) return false;
      if (LGOOOMGJKHH != other.LGOOOMGJKHH) return false;
      if (HKOGCPNHNCA != other.HKOGCPNHNCA) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IMGILNNKGEK != false) hash ^= IMGILNNKGEK.GetHashCode();
      if (GGPLKBFBPNP != 0) hash ^= GGPLKBFBPNP.GetHashCode();
      hash ^= buffList_.GetHashCode();
      if (MKKIBDNBNFE != false) hash ^= MKKIBDNBNFE.GetHashCode();
      if (EFKNEAIPGLF != false) hash ^= EFKNEAIPGLF.GetHashCode();
      if (LMCBFDAFMPP != false) hash ^= LMCBFDAFMPP.GetHashCode();
      if (LGOOOMGJKHH != 0) hash ^= LGOOOMGJKHH.GetHashCode();
      if (HKOGCPNHNCA != 0) hash ^= HKOGCPNHNCA.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EFKNEAIPGLF != false) {
        output.WriteRawTag(40);
        output.WriteBool(EFKNEAIPGLF);
      }
      if (GGPLKBFBPNP != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GGPLKBFBPNP);
      }
      if (IMGILNNKGEK != false) {
        output.WriteRawTag(72);
        output.WriteBool(IMGILNNKGEK);
      }
      if (LGOOOMGJKHH != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(LGOOOMGJKHH);
      }
      if (HKOGCPNHNCA != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(HKOGCPNHNCA);
      }
      if (MKKIBDNBNFE != false) {
        output.WriteRawTag(112);
        output.WriteBool(MKKIBDNBNFE);
      }
      if (LMCBFDAFMPP != false) {
        output.WriteRawTag(120);
        output.WriteBool(LMCBFDAFMPP);
      }
      buffList_.WriteTo(output, _repeated_buffList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EFKNEAIPGLF != false) {
        output.WriteRawTag(40);
        output.WriteBool(EFKNEAIPGLF);
      }
      if (GGPLKBFBPNP != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GGPLKBFBPNP);
      }
      if (IMGILNNKGEK != false) {
        output.WriteRawTag(72);
        output.WriteBool(IMGILNNKGEK);
      }
      if (LGOOOMGJKHH != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(LGOOOMGJKHH);
      }
      if (HKOGCPNHNCA != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(HKOGCPNHNCA);
      }
      if (MKKIBDNBNFE != false) {
        output.WriteRawTag(112);
        output.WriteBool(MKKIBDNBNFE);
      }
      if (LMCBFDAFMPP != false) {
        output.WriteRawTag(120);
        output.WriteBool(LMCBFDAFMPP);
      }
      buffList_.WriteTo(ref output, _repeated_buffList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IMGILNNKGEK != false) {
        size += 1 + 1;
      }
      if (GGPLKBFBPNP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GGPLKBFBPNP);
      }
      size += buffList_.CalculateSize(_repeated_buffList_codec);
      if (MKKIBDNBNFE != false) {
        size += 1 + 1;
      }
      if (EFKNEAIPGLF != false) {
        size += 1 + 1;
      }
      if (LMCBFDAFMPP != false) {
        size += 1 + 1;
      }
      if (LGOOOMGJKHH != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LGOOOMGJKHH);
      }
      if (HKOGCPNHNCA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HKOGCPNHNCA);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FODJFBNFPJC other) {
      if (other == null) {
        return;
      }
      if (other.IMGILNNKGEK != false) {
        IMGILNNKGEK = other.IMGILNNKGEK;
      }
      if (other.GGPLKBFBPNP != 0) {
        GGPLKBFBPNP = other.GGPLKBFBPNP;
      }
      buffList_.Add(other.buffList_);
      if (other.MKKIBDNBNFE != false) {
        MKKIBDNBNFE = other.MKKIBDNBNFE;
      }
      if (other.EFKNEAIPGLF != false) {
        EFKNEAIPGLF = other.EFKNEAIPGLF;
      }
      if (other.LMCBFDAFMPP != false) {
        LMCBFDAFMPP = other.LMCBFDAFMPP;
      }
      if (other.LGOOOMGJKHH != 0) {
        LGOOOMGJKHH = other.LGOOOMGJKHH;
      }
      if (other.HKOGCPNHNCA != 0) {
        HKOGCPNHNCA = other.HKOGCPNHNCA;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 40: {
            EFKNEAIPGLF = input.ReadBool();
            break;
          }
          case 64: {
            GGPLKBFBPNP = input.ReadUInt32();
            break;
          }
          case 72: {
            IMGILNNKGEK = input.ReadBool();
            break;
          }
          case 80: {
            LGOOOMGJKHH = input.ReadUInt32();
            break;
          }
          case 88: {
            HKOGCPNHNCA = input.ReadUInt32();
            break;
          }
          case 112: {
            MKKIBDNBNFE = input.ReadBool();
            break;
          }
          case 120: {
            LMCBFDAFMPP = input.ReadBool();
            break;
          }
          case 5954: {
            buffList_.AddEntriesFrom(input, _repeated_buffList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 40: {
            EFKNEAIPGLF = input.ReadBool();
            break;
          }
          case 64: {
            GGPLKBFBPNP = input.ReadUInt32();
            break;
          }
          case 72: {
            IMGILNNKGEK = input.ReadBool();
            break;
          }
          case 80: {
            LGOOOMGJKHH = input.ReadUInt32();
            break;
          }
          case 88: {
            HKOGCPNHNCA = input.ReadUInt32();
            break;
          }
          case 112: {
            MKKIBDNBNFE = input.ReadBool();
            break;
          }
          case 120: {
            LMCBFDAFMPP = input.ReadBool();
            break;
          }
          case 5954: {
            buffList_.AddEntriesFrom(ref input, _repeated_buffList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
