// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetBagScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from GetBagScRsp.proto</summary>
  public static partial class GetBagScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for GetBagScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetBagScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHZXRCYWdTY1JzcC5wcm90bxoOTWF0ZXJpYWwucHJvdG8aD01hdGVyaWFs",
            "MC5wcm90bxoVV2FpdERlbFJlc291cmNlLnByb3RvGgtSZWxpYy5wcm90bxoU",
            "VHVybkZvb2RTd2l0Y2gucHJvdG8aDlBpbGVJdGVtLnByb3RvGg9FcXVpcG1l",
            "bnQucHJvdG8ingMKC0dldEJhZ1NjUnNwEiIKDmVxdWlwbWVudF9saXN0GA8g",
            "AygLMgouRXF1aXBtZW50EiAKDW1hdGVyaWFsX2xpc3QYByADKAsyCS5NYXRl",
            "cmlhbBIPCgdyZXRjb2RlGAQgASgNEikKEHR1cm5fZm9vZF9zd2l0Y2gYCiAD",
            "KA4yDy5UdXJuRm9vZFN3aXRjaBITCgtDQkdQQ01LSU5PThgLIAMoDRIfCgtI",
            "T0RBTE5ISEpISBgCIAMoCzIKLk1hdGVyaWFsMBITCgtJR0VGT09ER0JPQxgG",
            "IAEoDRIaCgpyZWxpY19saXN0GAggAygLMgYuUmVsaWMSHgoLR2V0QmFnQ3NS",
            "ZXEYASADKAsyCS5QaWxlSXRlbRITCgtGUE5KTUxFRE9DQhgNIAMoDRIwChZ3",
            "YWl0X2RlbF9yZXNvdXJjZV9saXN0GAwgAygLMhAuV2FpdERlbFJlc291cmNl",
            "Eh4KC0hQT0NBTkZKT0xJGAUgAygLMgkuTWF0ZXJpYWwSHwoLT0xBREJKTlBE",
            "S1AYDiADKAsyCi5NYXRlcmlhbDBCHqoCG0VnZ0xpbmsuRGFuaGVuZ1NlcnZl",
            "ci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.MaterialReflection.Descriptor, global::EggLink.DanhengServer.Proto.Material0Reflection.Descriptor, global::EggLink.DanhengServer.Proto.WaitDelResourceReflection.Descriptor, global::EggLink.DanhengServer.Proto.RelicReflection.Descriptor, global::EggLink.DanhengServer.Proto.TurnFoodSwitchReflection.Descriptor, global::EggLink.DanhengServer.Proto.PileItemReflection.Descriptor, global::EggLink.DanhengServer.Proto.EquipmentReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.GetBagScRsp), global::EggLink.DanhengServer.Proto.GetBagScRsp.Parser, new[]{ "EquipmentList", "MaterialList", "Retcode", "TurnFoodSwitch", "CBGPCMKINON", "HODALNHHJHH", "IGEFOODGBOC", "RelicList", "GetBagCsReq", "FPNJMLEDOCB", "WaitDelResourceList", "HPOCANFJOLI", "OLADBJNPDKP" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetBagScRsp : pb::IMessage<GetBagScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetBagScRsp> _parser = new pb::MessageParser<GetBagScRsp>(() => new GetBagScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetBagScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.GetBagScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetBagScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetBagScRsp(GetBagScRsp other) : this() {
      equipmentList_ = other.equipmentList_.Clone();
      materialList_ = other.materialList_.Clone();
      retcode_ = other.retcode_;
      turnFoodSwitch_ = other.turnFoodSwitch_.Clone();
      cBGPCMKINON_ = other.cBGPCMKINON_.Clone();
      hODALNHHJHH_ = other.hODALNHHJHH_.Clone();
      iGEFOODGBOC_ = other.iGEFOODGBOC_;
      relicList_ = other.relicList_.Clone();
      getBagCsReq_ = other.getBagCsReq_.Clone();
      fPNJMLEDOCB_ = other.fPNJMLEDOCB_.Clone();
      waitDelResourceList_ = other.waitDelResourceList_.Clone();
      hPOCANFJOLI_ = other.hPOCANFJOLI_.Clone();
      oLADBJNPDKP_ = other.oLADBJNPDKP_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetBagScRsp Clone() {
      return new GetBagScRsp(this);
    }

    /// <summary>Field number for the "equipment_list" field.</summary>
    public const int EquipmentListFieldNumber = 15;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Equipment> _repeated_equipmentList_codec
        = pb::FieldCodec.ForMessage(122, global::EggLink.DanhengServer.Proto.Equipment.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Equipment> equipmentList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Equipment>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Equipment> EquipmentList {
      get { return equipmentList_; }
    }

    /// <summary>Field number for the "material_list" field.</summary>
    public const int MaterialListFieldNumber = 7;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Material> _repeated_materialList_codec
        = pb::FieldCodec.ForMessage(58, global::EggLink.DanhengServer.Proto.Material.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material> materialList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material> MaterialList {
      get { return materialList_; }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 4;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "turn_food_switch" field.</summary>
    public const int TurnFoodSwitchFieldNumber = 10;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.TurnFoodSwitch> _repeated_turnFoodSwitch_codec
        = pb::FieldCodec.ForEnum(82, x => (int) x, x => (global::EggLink.DanhengServer.Proto.TurnFoodSwitch) x);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.TurnFoodSwitch> turnFoodSwitch_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.TurnFoodSwitch>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.TurnFoodSwitch> TurnFoodSwitch {
      get { return turnFoodSwitch_; }
    }

    /// <summary>Field number for the "CBGPCMKINON" field.</summary>
    public const int CBGPCMKINONFieldNumber = 11;
    private static readonly pb::FieldCodec<uint> _repeated_cBGPCMKINON_codec
        = pb::FieldCodec.ForUInt32(90);
    private readonly pbc::RepeatedField<uint> cBGPCMKINON_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> CBGPCMKINON {
      get { return cBGPCMKINON_; }
    }

    /// <summary>Field number for the "HODALNHHJHH" field.</summary>
    public const int HODALNHHJHHFieldNumber = 2;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Material0> _repeated_hODALNHHJHH_codec
        = pb::FieldCodec.ForMessage(18, global::EggLink.DanhengServer.Proto.Material0.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0> hODALNHHJHH_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0> HODALNHHJHH {
      get { return hODALNHHJHH_; }
    }

    /// <summary>Field number for the "IGEFOODGBOC" field.</summary>
    public const int IGEFOODGBOCFieldNumber = 6;
    private uint iGEFOODGBOC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IGEFOODGBOC {
      get { return iGEFOODGBOC_; }
      set {
        iGEFOODGBOC_ = value;
      }
    }

    /// <summary>Field number for the "relic_list" field.</summary>
    public const int RelicListFieldNumber = 8;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Relic> _repeated_relicList_codec
        = pb::FieldCodec.ForMessage(66, global::EggLink.DanhengServer.Proto.Relic.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Relic> relicList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Relic>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Relic> RelicList {
      get { return relicList_; }
    }

    /// <summary>Field number for the "GetBagCsReq" field.</summary>
    public const int GetBagCsReqFieldNumber = 1;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.PileItem> _repeated_getBagCsReq_codec
        = pb::FieldCodec.ForMessage(10, global::EggLink.DanhengServer.Proto.PileItem.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PileItem> getBagCsReq_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PileItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PileItem> GetBagCsReq {
      get { return getBagCsReq_; }
    }

    /// <summary>Field number for the "FPNJMLEDOCB" field.</summary>
    public const int FPNJMLEDOCBFieldNumber = 13;
    private static readonly pb::FieldCodec<uint> _repeated_fPNJMLEDOCB_codec
        = pb::FieldCodec.ForUInt32(106);
    private readonly pbc::RepeatedField<uint> fPNJMLEDOCB_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> FPNJMLEDOCB {
      get { return fPNJMLEDOCB_; }
    }

    /// <summary>Field number for the "wait_del_resource_list" field.</summary>
    public const int WaitDelResourceListFieldNumber = 12;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.WaitDelResource> _repeated_waitDelResourceList_codec
        = pb::FieldCodec.ForMessage(98, global::EggLink.DanhengServer.Proto.WaitDelResource.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.WaitDelResource> waitDelResourceList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.WaitDelResource>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.WaitDelResource> WaitDelResourceList {
      get { return waitDelResourceList_; }
    }

    /// <summary>Field number for the "HPOCANFJOLI" field.</summary>
    public const int HPOCANFJOLIFieldNumber = 5;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Material> _repeated_hPOCANFJOLI_codec
        = pb::FieldCodec.ForMessage(42, global::EggLink.DanhengServer.Proto.Material.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material> hPOCANFJOLI_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material> HPOCANFJOLI {
      get { return hPOCANFJOLI_; }
    }

    /// <summary>Field number for the "OLADBJNPDKP" field.</summary>
    public const int OLADBJNPDKPFieldNumber = 14;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Material0> _repeated_oLADBJNPDKP_codec
        = pb::FieldCodec.ForMessage(114, global::EggLink.DanhengServer.Proto.Material0.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0> oLADBJNPDKP_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0> OLADBJNPDKP {
      get { return oLADBJNPDKP_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetBagScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetBagScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!equipmentList_.Equals(other.equipmentList_)) return false;
      if(!materialList_.Equals(other.materialList_)) return false;
      if (Retcode != other.Retcode) return false;
      if(!turnFoodSwitch_.Equals(other.turnFoodSwitch_)) return false;
      if(!cBGPCMKINON_.Equals(other.cBGPCMKINON_)) return false;
      if(!hODALNHHJHH_.Equals(other.hODALNHHJHH_)) return false;
      if (IGEFOODGBOC != other.IGEFOODGBOC) return false;
      if(!relicList_.Equals(other.relicList_)) return false;
      if(!getBagCsReq_.Equals(other.getBagCsReq_)) return false;
      if(!fPNJMLEDOCB_.Equals(other.fPNJMLEDOCB_)) return false;
      if(!waitDelResourceList_.Equals(other.waitDelResourceList_)) return false;
      if(!hPOCANFJOLI_.Equals(other.hPOCANFJOLI_)) return false;
      if(!oLADBJNPDKP_.Equals(other.oLADBJNPDKP_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= equipmentList_.GetHashCode();
      hash ^= materialList_.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      hash ^= turnFoodSwitch_.GetHashCode();
      hash ^= cBGPCMKINON_.GetHashCode();
      hash ^= hODALNHHJHH_.GetHashCode();
      if (IGEFOODGBOC != 0) hash ^= IGEFOODGBOC.GetHashCode();
      hash ^= relicList_.GetHashCode();
      hash ^= getBagCsReq_.GetHashCode();
      hash ^= fPNJMLEDOCB_.GetHashCode();
      hash ^= waitDelResourceList_.GetHashCode();
      hash ^= hPOCANFJOLI_.GetHashCode();
      hash ^= oLADBJNPDKP_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      getBagCsReq_.WriteTo(output, _repeated_getBagCsReq_codec);
      hODALNHHJHH_.WriteTo(output, _repeated_hODALNHHJHH_codec);
      if (Retcode != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Retcode);
      }
      hPOCANFJOLI_.WriteTo(output, _repeated_hPOCANFJOLI_codec);
      if (IGEFOODGBOC != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(IGEFOODGBOC);
      }
      materialList_.WriteTo(output, _repeated_materialList_codec);
      relicList_.WriteTo(output, _repeated_relicList_codec);
      turnFoodSwitch_.WriteTo(output, _repeated_turnFoodSwitch_codec);
      cBGPCMKINON_.WriteTo(output, _repeated_cBGPCMKINON_codec);
      waitDelResourceList_.WriteTo(output, _repeated_waitDelResourceList_codec);
      fPNJMLEDOCB_.WriteTo(output, _repeated_fPNJMLEDOCB_codec);
      oLADBJNPDKP_.WriteTo(output, _repeated_oLADBJNPDKP_codec);
      equipmentList_.WriteTo(output, _repeated_equipmentList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      getBagCsReq_.WriteTo(ref output, _repeated_getBagCsReq_codec);
      hODALNHHJHH_.WriteTo(ref output, _repeated_hODALNHHJHH_codec);
      if (Retcode != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Retcode);
      }
      hPOCANFJOLI_.WriteTo(ref output, _repeated_hPOCANFJOLI_codec);
      if (IGEFOODGBOC != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(IGEFOODGBOC);
      }
      materialList_.WriteTo(ref output, _repeated_materialList_codec);
      relicList_.WriteTo(ref output, _repeated_relicList_codec);
      turnFoodSwitch_.WriteTo(ref output, _repeated_turnFoodSwitch_codec);
      cBGPCMKINON_.WriteTo(ref output, _repeated_cBGPCMKINON_codec);
      waitDelResourceList_.WriteTo(ref output, _repeated_waitDelResourceList_codec);
      fPNJMLEDOCB_.WriteTo(ref output, _repeated_fPNJMLEDOCB_codec);
      oLADBJNPDKP_.WriteTo(ref output, _repeated_oLADBJNPDKP_codec);
      equipmentList_.WriteTo(ref output, _repeated_equipmentList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += equipmentList_.CalculateSize(_repeated_equipmentList_codec);
      size += materialList_.CalculateSize(_repeated_materialList_codec);
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      size += turnFoodSwitch_.CalculateSize(_repeated_turnFoodSwitch_codec);
      size += cBGPCMKINON_.CalculateSize(_repeated_cBGPCMKINON_codec);
      size += hODALNHHJHH_.CalculateSize(_repeated_hODALNHHJHH_codec);
      if (IGEFOODGBOC != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IGEFOODGBOC);
      }
      size += relicList_.CalculateSize(_repeated_relicList_codec);
      size += getBagCsReq_.CalculateSize(_repeated_getBagCsReq_codec);
      size += fPNJMLEDOCB_.CalculateSize(_repeated_fPNJMLEDOCB_codec);
      size += waitDelResourceList_.CalculateSize(_repeated_waitDelResourceList_codec);
      size += hPOCANFJOLI_.CalculateSize(_repeated_hPOCANFJOLI_codec);
      size += oLADBJNPDKP_.CalculateSize(_repeated_oLADBJNPDKP_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetBagScRsp other) {
      if (other == null) {
        return;
      }
      equipmentList_.Add(other.equipmentList_);
      materialList_.Add(other.materialList_);
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      turnFoodSwitch_.Add(other.turnFoodSwitch_);
      cBGPCMKINON_.Add(other.cBGPCMKINON_);
      hODALNHHJHH_.Add(other.hODALNHHJHH_);
      if (other.IGEFOODGBOC != 0) {
        IGEFOODGBOC = other.IGEFOODGBOC;
      }
      relicList_.Add(other.relicList_);
      getBagCsReq_.Add(other.getBagCsReq_);
      fPNJMLEDOCB_.Add(other.fPNJMLEDOCB_);
      waitDelResourceList_.Add(other.waitDelResourceList_);
      hPOCANFJOLI_.Add(other.hPOCANFJOLI_);
      oLADBJNPDKP_.Add(other.oLADBJNPDKP_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            getBagCsReq_.AddEntriesFrom(input, _repeated_getBagCsReq_codec);
            break;
          }
          case 18: {
            hODALNHHJHH_.AddEntriesFrom(input, _repeated_hODALNHHJHH_codec);
            break;
          }
          case 32: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 42: {
            hPOCANFJOLI_.AddEntriesFrom(input, _repeated_hPOCANFJOLI_codec);
            break;
          }
          case 48: {
            IGEFOODGBOC = input.ReadUInt32();
            break;
          }
          case 58: {
            materialList_.AddEntriesFrom(input, _repeated_materialList_codec);
            break;
          }
          case 66: {
            relicList_.AddEntriesFrom(input, _repeated_relicList_codec);
            break;
          }
          case 82:
          case 80: {
            turnFoodSwitch_.AddEntriesFrom(input, _repeated_turnFoodSwitch_codec);
            break;
          }
          case 90:
          case 88: {
            cBGPCMKINON_.AddEntriesFrom(input, _repeated_cBGPCMKINON_codec);
            break;
          }
          case 98: {
            waitDelResourceList_.AddEntriesFrom(input, _repeated_waitDelResourceList_codec);
            break;
          }
          case 106:
          case 104: {
            fPNJMLEDOCB_.AddEntriesFrom(input, _repeated_fPNJMLEDOCB_codec);
            break;
          }
          case 114: {
            oLADBJNPDKP_.AddEntriesFrom(input, _repeated_oLADBJNPDKP_codec);
            break;
          }
          case 122: {
            equipmentList_.AddEntriesFrom(input, _repeated_equipmentList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            getBagCsReq_.AddEntriesFrom(ref input, _repeated_getBagCsReq_codec);
            break;
          }
          case 18: {
            hODALNHHJHH_.AddEntriesFrom(ref input, _repeated_hODALNHHJHH_codec);
            break;
          }
          case 32: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 42: {
            hPOCANFJOLI_.AddEntriesFrom(ref input, _repeated_hPOCANFJOLI_codec);
            break;
          }
          case 48: {
            IGEFOODGBOC = input.ReadUInt32();
            break;
          }
          case 58: {
            materialList_.AddEntriesFrom(ref input, _repeated_materialList_codec);
            break;
          }
          case 66: {
            relicList_.AddEntriesFrom(ref input, _repeated_relicList_codec);
            break;
          }
          case 82:
          case 80: {
            turnFoodSwitch_.AddEntriesFrom(ref input, _repeated_turnFoodSwitch_codec);
            break;
          }
          case 90:
          case 88: {
            cBGPCMKINON_.AddEntriesFrom(ref input, _repeated_cBGPCMKINON_codec);
            break;
          }
          case 98: {
            waitDelResourceList_.AddEntriesFrom(ref input, _repeated_waitDelResourceList_codec);
            break;
          }
          case 106:
          case 104: {
            fPNJMLEDOCB_.AddEntriesFrom(ref input, _repeated_fPNJMLEDOCB_codec);
            break;
          }
          case 114: {
            oLADBJNPDKP_.AddEntriesFrom(ref input, _repeated_oLADBJNPDKP_codec);
            break;
          }
          case 122: {
            equipmentList_.AddEntriesFrom(ref input, _repeated_equipmentList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
