// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetWaypointScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from GetWaypointScRsp.proto</summary>
  public static partial class GetWaypointScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for GetWaypointScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetWaypointScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZHZXRXYXlwb2ludFNjUnNwLnByb3RvGg1DaGFwdGVyLnByb3RvIlcKEEdl",
            "dFdheXBvaW50U2NSc3ASEwoLTUNDRkJMQVBOTEMYDiABKA0SDwoHcmV0Y29k",
            "ZRgDIAEoDRIdCgtLQ09QUEhNQUVQSxgGIAEoCzIILkNoYXB0ZXJCHqoCG0Vn",
            "Z0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.ChapterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.GetWaypointScRsp), global::EggLink.DanhengServer.Proto.GetWaypointScRsp.Parser, new[]{ "MCCFBLAPNLC", "Retcode", "KCOPPHMAEPK" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetWaypointScRsp : pb::IMessage<GetWaypointScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetWaypointScRsp> _parser = new pb::MessageParser<GetWaypointScRsp>(() => new GetWaypointScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetWaypointScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.GetWaypointScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetWaypointScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetWaypointScRsp(GetWaypointScRsp other) : this() {
      mCCFBLAPNLC_ = other.mCCFBLAPNLC_;
      retcode_ = other.retcode_;
      kCOPPHMAEPK_ = other.kCOPPHMAEPK_ != null ? other.kCOPPHMAEPK_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetWaypointScRsp Clone() {
      return new GetWaypointScRsp(this);
    }

    /// <summary>Field number for the "MCCFBLAPNLC" field.</summary>
    public const int MCCFBLAPNLCFieldNumber = 14;
    private uint mCCFBLAPNLC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MCCFBLAPNLC {
      get { return mCCFBLAPNLC_; }
      set {
        mCCFBLAPNLC_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 3;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "KCOPPHMAEPK" field.</summary>
    public const int KCOPPHMAEPKFieldNumber = 6;
    private global::EggLink.DanhengServer.Proto.Chapter kCOPPHMAEPK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.Chapter KCOPPHMAEPK {
      get { return kCOPPHMAEPK_; }
      set {
        kCOPPHMAEPK_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetWaypointScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetWaypointScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MCCFBLAPNLC != other.MCCFBLAPNLC) return false;
      if (Retcode != other.Retcode) return false;
      if (!object.Equals(KCOPPHMAEPK, other.KCOPPHMAEPK)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MCCFBLAPNLC != 0) hash ^= MCCFBLAPNLC.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (kCOPPHMAEPK_ != null) hash ^= KCOPPHMAEPK.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Retcode != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Retcode);
      }
      if (kCOPPHMAEPK_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(KCOPPHMAEPK);
      }
      if (MCCFBLAPNLC != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(MCCFBLAPNLC);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Retcode != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Retcode);
      }
      if (kCOPPHMAEPK_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(KCOPPHMAEPK);
      }
      if (MCCFBLAPNLC != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(MCCFBLAPNLC);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MCCFBLAPNLC != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MCCFBLAPNLC);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (kCOPPHMAEPK_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(KCOPPHMAEPK);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetWaypointScRsp other) {
      if (other == null) {
        return;
      }
      if (other.MCCFBLAPNLC != 0) {
        MCCFBLAPNLC = other.MCCFBLAPNLC;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.kCOPPHMAEPK_ != null) {
        if (kCOPPHMAEPK_ == null) {
          KCOPPHMAEPK = new global::EggLink.DanhengServer.Proto.Chapter();
        }
        KCOPPHMAEPK.MergeFrom(other.KCOPPHMAEPK);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 50: {
            if (kCOPPHMAEPK_ == null) {
              KCOPPHMAEPK = new global::EggLink.DanhengServer.Proto.Chapter();
            }
            input.ReadMessage(KCOPPHMAEPK);
            break;
          }
          case 112: {
            MCCFBLAPNLC = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 50: {
            if (kCOPPHMAEPK_ == null) {
              KCOPPHMAEPK = new global::EggLink.DanhengServer.Proto.Chapter();
            }
            input.ReadMessage(KCOPPHMAEPK);
            break;
          }
          case 112: {
            MCCFBLAPNLC = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
