// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IFNOEFNECDB.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from IFNOEFNECDB.proto</summary>
  public static partial class IFNOEFNECDBReflection {

    #region Descriptor
    /// <summary>File descriptor for IFNOEFNECDB.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IFNOEFNECDBReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFJRk5PRUZORUNEQi5wcm90bxoSSXRlbUNvc3REYXRhLnByb3RvIoMBCgtJ",
            "Rk5PRUZORUNEQhITCgtFTU1QQ09JSFBEQRgGIAEoBRITCgtQRkZFQkFETUZK",
            "ThgNIAEoDRITCgtQSkxPS05ESUVHRxgEIAEoCBITCgtLQ05KTUFKQkhQSRgC",
            "IAEoDRIgCgljb3N0X2RhdGEYASABKAsyDS5JdGVtQ29zdERhdGFCHqoCG0Vn",
            "Z0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.ItemCostDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.IFNOEFNECDB), global::EggLink.DanhengServer.Proto.IFNOEFNECDB.Parser, new[]{ "EMMPCOIHPDA", "PFFEBADMFJN", "PJLOKNDIEGG", "KCNJMAJBHPI", "CostData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class IFNOEFNECDB : pb::IMessage<IFNOEFNECDB>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IFNOEFNECDB> _parser = new pb::MessageParser<IFNOEFNECDB>(() => new IFNOEFNECDB());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IFNOEFNECDB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.IFNOEFNECDBReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IFNOEFNECDB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IFNOEFNECDB(IFNOEFNECDB other) : this() {
      eMMPCOIHPDA_ = other.eMMPCOIHPDA_;
      pFFEBADMFJN_ = other.pFFEBADMFJN_;
      pJLOKNDIEGG_ = other.pJLOKNDIEGG_;
      kCNJMAJBHPI_ = other.kCNJMAJBHPI_;
      costData_ = other.costData_ != null ? other.costData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IFNOEFNECDB Clone() {
      return new IFNOEFNECDB(this);
    }

    /// <summary>Field number for the "EMMPCOIHPDA" field.</summary>
    public const int EMMPCOIHPDAFieldNumber = 6;
    private int eMMPCOIHPDA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EMMPCOIHPDA {
      get { return eMMPCOIHPDA_; }
      set {
        eMMPCOIHPDA_ = value;
      }
    }

    /// <summary>Field number for the "PFFEBADMFJN" field.</summary>
    public const int PFFEBADMFJNFieldNumber = 13;
    private uint pFFEBADMFJN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PFFEBADMFJN {
      get { return pFFEBADMFJN_; }
      set {
        pFFEBADMFJN_ = value;
      }
    }

    /// <summary>Field number for the "PJLOKNDIEGG" field.</summary>
    public const int PJLOKNDIEGGFieldNumber = 4;
    private bool pJLOKNDIEGG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PJLOKNDIEGG {
      get { return pJLOKNDIEGG_; }
      set {
        pJLOKNDIEGG_ = value;
      }
    }

    /// <summary>Field number for the "KCNJMAJBHPI" field.</summary>
    public const int KCNJMAJBHPIFieldNumber = 2;
    private uint kCNJMAJBHPI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KCNJMAJBHPI {
      get { return kCNJMAJBHPI_; }
      set {
        kCNJMAJBHPI_ = value;
      }
    }

    /// <summary>Field number for the "cost_data" field.</summary>
    public const int CostDataFieldNumber = 1;
    private global::EggLink.DanhengServer.Proto.ItemCostData costData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ItemCostData CostData {
      get { return costData_; }
      set {
        costData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IFNOEFNECDB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IFNOEFNECDB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EMMPCOIHPDA != other.EMMPCOIHPDA) return false;
      if (PFFEBADMFJN != other.PFFEBADMFJN) return false;
      if (PJLOKNDIEGG != other.PJLOKNDIEGG) return false;
      if (KCNJMAJBHPI != other.KCNJMAJBHPI) return false;
      if (!object.Equals(CostData, other.CostData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EMMPCOIHPDA != 0) hash ^= EMMPCOIHPDA.GetHashCode();
      if (PFFEBADMFJN != 0) hash ^= PFFEBADMFJN.GetHashCode();
      if (PJLOKNDIEGG != false) hash ^= PJLOKNDIEGG.GetHashCode();
      if (KCNJMAJBHPI != 0) hash ^= KCNJMAJBHPI.GetHashCode();
      if (costData_ != null) hash ^= CostData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (costData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CostData);
      }
      if (KCNJMAJBHPI != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(KCNJMAJBHPI);
      }
      if (PJLOKNDIEGG != false) {
        output.WriteRawTag(32);
        output.WriteBool(PJLOKNDIEGG);
      }
      if (EMMPCOIHPDA != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(EMMPCOIHPDA);
      }
      if (PFFEBADMFJN != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(PFFEBADMFJN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (costData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CostData);
      }
      if (KCNJMAJBHPI != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(KCNJMAJBHPI);
      }
      if (PJLOKNDIEGG != false) {
        output.WriteRawTag(32);
        output.WriteBool(PJLOKNDIEGG);
      }
      if (EMMPCOIHPDA != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(EMMPCOIHPDA);
      }
      if (PFFEBADMFJN != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(PFFEBADMFJN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EMMPCOIHPDA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EMMPCOIHPDA);
      }
      if (PFFEBADMFJN != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PFFEBADMFJN);
      }
      if (PJLOKNDIEGG != false) {
        size += 1 + 1;
      }
      if (KCNJMAJBHPI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KCNJMAJBHPI);
      }
      if (costData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CostData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IFNOEFNECDB other) {
      if (other == null) {
        return;
      }
      if (other.EMMPCOIHPDA != 0) {
        EMMPCOIHPDA = other.EMMPCOIHPDA;
      }
      if (other.PFFEBADMFJN != 0) {
        PFFEBADMFJN = other.PFFEBADMFJN;
      }
      if (other.PJLOKNDIEGG != false) {
        PJLOKNDIEGG = other.PJLOKNDIEGG;
      }
      if (other.KCNJMAJBHPI != 0) {
        KCNJMAJBHPI = other.KCNJMAJBHPI;
      }
      if (other.costData_ != null) {
        if (costData_ == null) {
          CostData = new global::EggLink.DanhengServer.Proto.ItemCostData();
        }
        CostData.MergeFrom(other.CostData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (costData_ == null) {
              CostData = new global::EggLink.DanhengServer.Proto.ItemCostData();
            }
            input.ReadMessage(CostData);
            break;
          }
          case 16: {
            KCNJMAJBHPI = input.ReadUInt32();
            break;
          }
          case 32: {
            PJLOKNDIEGG = input.ReadBool();
            break;
          }
          case 48: {
            EMMPCOIHPDA = input.ReadInt32();
            break;
          }
          case 104: {
            PFFEBADMFJN = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (costData_ == null) {
              CostData = new global::EggLink.DanhengServer.Proto.ItemCostData();
            }
            input.ReadMessage(CostData);
            break;
          }
          case 16: {
            KCNJMAJBHPI = input.ReadUInt32();
            break;
          }
          case 32: {
            PJLOKNDIEGG = input.ReadBool();
            break;
          }
          case 48: {
            EMMPCOIHPDA = input.ReadInt32();
            break;
          }
          case 104: {
            PFFEBADMFJN = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
