// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LKIKJEIOEIH.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from LKIKJEIOEIH.proto</summary>
  public static partial class LKIKJEIOEIHReflection {

    #region Descriptor
    /// <summary>File descriptor for LKIKJEIOEIH.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LKIKJEIOEIHReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMS0lLSkVJT0VJSC5wcm90byI3CgtMS0lLSkVJT0VJSBITCgtFSkVLQlBI",
            "Qk9NSxgOIAMoDRITCgtEUERLSU5ITUZOTxgKIAEoDUIeqgIbRWdnTGluay5E",
            "YW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.LKIKJEIOEIH), global::EggLink.DanhengServer.Proto.LKIKJEIOEIH.Parser, new[]{ "EJEKBPHBOMK", "DPDKINHMFNO" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LKIKJEIOEIH : pb::IMessage<LKIKJEIOEIH>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LKIKJEIOEIH> _parser = new pb::MessageParser<LKIKJEIOEIH>(() => new LKIKJEIOEIH());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LKIKJEIOEIH> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.LKIKJEIOEIHReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LKIKJEIOEIH() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LKIKJEIOEIH(LKIKJEIOEIH other) : this() {
      eJEKBPHBOMK_ = other.eJEKBPHBOMK_.Clone();
      dPDKINHMFNO_ = other.dPDKINHMFNO_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LKIKJEIOEIH Clone() {
      return new LKIKJEIOEIH(this);
    }

    /// <summary>Field number for the "EJEKBPHBOMK" field.</summary>
    public const int EJEKBPHBOMKFieldNumber = 14;
    private static readonly pb::FieldCodec<uint> _repeated_eJEKBPHBOMK_codec
        = pb::FieldCodec.ForUInt32(114);
    private readonly pbc::RepeatedField<uint> eJEKBPHBOMK_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> EJEKBPHBOMK {
      get { return eJEKBPHBOMK_; }
    }

    /// <summary>Field number for the "DPDKINHMFNO" field.</summary>
    public const int DPDKINHMFNOFieldNumber = 10;
    private uint dPDKINHMFNO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DPDKINHMFNO {
      get { return dPDKINHMFNO_; }
      set {
        dPDKINHMFNO_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LKIKJEIOEIH);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LKIKJEIOEIH other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!eJEKBPHBOMK_.Equals(other.eJEKBPHBOMK_)) return false;
      if (DPDKINHMFNO != other.DPDKINHMFNO) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= eJEKBPHBOMK_.GetHashCode();
      if (DPDKINHMFNO != 0) hash ^= DPDKINHMFNO.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DPDKINHMFNO != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(DPDKINHMFNO);
      }
      eJEKBPHBOMK_.WriteTo(output, _repeated_eJEKBPHBOMK_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DPDKINHMFNO != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(DPDKINHMFNO);
      }
      eJEKBPHBOMK_.WriteTo(ref output, _repeated_eJEKBPHBOMK_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += eJEKBPHBOMK_.CalculateSize(_repeated_eJEKBPHBOMK_codec);
      if (DPDKINHMFNO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DPDKINHMFNO);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LKIKJEIOEIH other) {
      if (other == null) {
        return;
      }
      eJEKBPHBOMK_.Add(other.eJEKBPHBOMK_);
      if (other.DPDKINHMFNO != 0) {
        DPDKINHMFNO = other.DPDKINHMFNO;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 80: {
            DPDKINHMFNO = input.ReadUInt32();
            break;
          }
          case 114:
          case 112: {
            eJEKBPHBOMK_.AddEntriesFrom(input, _repeated_eJEKBPHBOMK_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 80: {
            DPDKINHMFNO = input.ReadUInt32();
            break;
          }
          case 114:
          case 112: {
            eJEKBPHBOMK_.AddEntriesFrom(ref input, _repeated_eJEKBPHBOMK_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
