// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TrackMainMissionUpdate.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from TrackMainMissionUpdate.proto</summary>
  public static partial class TrackMainMissionUpdateReflection {

    #region Descriptor
    /// <summary>File descriptor for TrackMainMissionUpdate.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrackMainMissionUpdateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxUcmFja01haW5NaXNzaW9uVXBkYXRlLnByb3RvKrIBChZUcmFja01haW5N",
            "aXNzaW9uVXBkYXRlEiIKHlRSQUNLX01BSU5fTUlTU0lPTl9VUERBVEVfTk9O",
            "RRAAEiIKHlRSQUNLX01BSU5fTUlTU0lPTl9VUERBVEVfQVVUTxABEiQKIFRS",
            "QUNLX01BSU5fTUlTU0lPTl9VUERBVEVfTUFOVUFMEAISKgomVFJBQ0tfTUFJ",
            "Tl9NSVNTSU9OX1VQREFURV9MT0dJTl9SRVBPUlQQA0IeqgIbRWdnTGluay5E",
            "YW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EggLink.DanhengServer.Proto.TrackMainMissionUpdate), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TrackMainMissionUpdate {
    [pbr::OriginalName("TRACK_MAIN_MISSION_UPDATE_NONE")] None = 0,
    [pbr::OriginalName("TRACK_MAIN_MISSION_UPDATE_AUTO")] Auto = 1,
    [pbr::OriginalName("TRACK_MAIN_MISSION_UPDATE_MANUAL")] Manual = 2,
    [pbr::OriginalName("TRACK_MAIN_MISSION_UPDATE_LOGIN_REPORT")] LoginReport = 3,
  }

  #endregion

}

#endregion Designer generated code
